### ISSUE TITLE
構文解析

### ISSUE THREAD

**Issue by harsssh** [harsssh/minishell#7]
入力の字句解析, 構文解析をやる.

**Comment by EringiShimeji** [comment]
エラーはパーサーエラー（syntax error）のみっぽい？

例えば`echo &&&&`みたいな入力だと

> bash: syntax error near unexpected token `&&'
というエラーが出るが、これは`&&`を一つのトークンとして認識した後に出るエラーなので、構文解析時に出ていると断定できる

そこで、今回実装しない演算子`&`や`;`などは特別な意味を持たない記号として扱い、トークンには変換しない予定

**Comment by EringiShimeji** [comment]
here-documentのtmpファイル作成は、AST作成後に行う。
AST全体を走査して、N_COMMANDタイプのノードのredirectsメンバの各要素について、REDIRECT_HERE_DOCタイプであれば、tmpファイルを作成しfilenameメンバにファイル名を格納する
tmpファイル作成中にエラーが発生した場合は、上流フローまで伝播させてファイルが作成できなかった旨をエラーメッセージとして吐き出させる。すなわち、syntax errorとは別のエラーを出す

**Comment by EringiShimeji** [comment]
tmpファイルの作成と書き込み、本当は子プロセスでやってるみたいだけど怖いのでメインプロセスでやります

**Comment by EringiShimeji** [comment]
パース後にASTを走査してargvとredirectsのfilenameに対して変数展開を行う。この時、変数名が存在しないか変数の中身が空文字列なら、argvとfilenameでそれぞれ次のような処理を行う。
- argvに対しては、変数展開できなかった要素を削除する。
- filenameに対しては、元の文字列をfreeしNULLを入れる。executorではfilenameがNULLの場合は`ambiguos redirect`というエラーを出す

**Comment by EringiShimeji** [comment]
パーサーのエラーメッセージはエラーが発生したタイミングで標準出力する

**Comment by EringiShimeji** [comment]
```
$> ""
bash: : command not found
$>  ''
bash: : command not found
$> echo "" a "" | cat -e
 a $
$> a=""
$> $a  <- 新しいプロンプトが出るだけ
$> echo $a a $a | cat -e
a$
```

**Comment by EringiShimeji** [comment]
変数展開したwordをASTに入れて、quote removalは評価器側でやってるっぽい？
変数展開した段階でwordが空文字になってたらargvから除去するのかも。
bashのソースコード見てないので後ほど調査します。

**Comment by EringiShimeji** [comment]
[ここ](https://github.com/bminor/bash/blob/master/parse.y#L6072C7-L6072C17)の条件的に、変数が文字列に含まれているならばquote removalはパーサーでしないのかもしれない。

**Comment by EringiShimeji** [comment]
答えはここにありました
https://github.com/bminor/bash/blob/ec8113b9861375e4e17b3307372569d429dec814/subst.c#L12845C6-L12848C39

**Comment by EringiShimeji** [comment]
https://www.gnu.org/software/bash/manual/bash.html#:~:text=Note%20that%20if%20no%20expansion%20occurs%2C%20no%20splitting%20is%20performed.
ここにもあった
